// Manual Portfolio Management — Phase G.3. Design:
// docs/REAL_PORTFOLIO_MODEL_BRIEF.md §13 ("v0.1 — Manual setup: Users can
// add holdings/cash manually. Ownership and transaction facts are
// user-maintained; market values come from live pricing where available").
//
// Pure, React-free form input -> Holding construction/validation. Ids are
// generated by the caller (crypto.randomUUID() at the UI layer) and passed
// in, so these functions stay deterministic and testable — no hidden
// randomness or clock reads here.
//
// nativeCurrency is intentionally NOT a form field: every holding is
// created in the portfolio's base currency (EUR for v0.1). No FX provider
// is wired (brief §8), so letting a holding be created in another currency
// would silently make it permanently MISSING rather than a real choice.
import type { AssetType, CostBasis, Holding, InstrumentIdentity } from "@/types/portfolio";

export interface HoldingFormInput {
  assetType: AssetType;
  name: string;
  ticker?: string;
  exchange?: string;
  isin?: string;
  // Cash amount for CASH; shares/units for everything else.
  quantity: number;
  // Per-unit cost, in the base currency. Omitted -> CostBasis MISSING (a
  // known holding with unknown cost history), never fabricated as 0.
  // Ignored for CASH, which is always NOT_APPLICABLE.
  averageCostNative?: number;
  // Manually entered current price, per unit, in the base currency —
  // there is no live quote provider wired, so this is the only source of
  // "what is it worth now" for a manually added holding (brief §9/§13).
  // Ignored for CASH (cash has no price concept — quantity IS the value).
  // Omitted -> the holding's value is honestly MISSING until priced.
  currentPriceNative?: number;
}

export interface HoldingFormValidation {
  valid: boolean;
  errors: string[];
}

// OTHER may have no ticker (brief's own InstrumentIdentity comment: "may
// be absent for OTHER"); CASH never has one; STOCK/ETF/CRYPTO need one to
// be identifiable at all.
function tickerRequired(assetType: AssetType): boolean {
  return assetType === "STOCK" || assetType === "ETF" || assetType === "CRYPTO";
}

export function validateHoldingFormInput(input: HoldingFormInput): HoldingFormValidation {
  const errors: string[] = [];

  if (!input.name.trim()) {
    errors.push("Name is required.");
  }
  if (!Number.isFinite(input.quantity) || input.quantity <= 0) {
    errors.push(
      input.assetType === "CASH" ? "Cash amount must be greater than 0." : "Quantity must be greater than 0."
    );
  }
  if (tickerRequired(input.assetType) && !input.ticker?.trim()) {
    errors.push("Ticker is required for this asset type.");
  }
  if (
    input.assetType !== "CASH" &&
    input.averageCostNative !== undefined &&
    (!Number.isFinite(input.averageCostNative) || input.averageCostNative < 0)
  ) {
    errors.push("Average cost must be zero or greater.");
  }
  if (
    input.assetType !== "CASH" &&
    input.currentPriceNative !== undefined &&
    (!Number.isFinite(input.currentPriceNative) || input.currentPriceNative <= 0)
  ) {
    errors.push("Current price must be greater than 0.");
  }

  return { valid: errors.length === 0, errors };
}

function buildCostBasis(assetType: AssetType, averageCostNative: number | undefined, asOf: string): CostBasis {
  if (assetType === "CASH") return { status: "NOT_APPLICABLE" };
  if (averageCostNative === undefined) return { status: "MISSING" };
  return { status: "AVAILABLE", averageCostNative, asOf };
}

function buildInstrument(
  input: HoldingFormInput,
  assetType: AssetType,
  instrumentId: string,
  baseCurrency: string
): InstrumentIdentity {
  return {
    id: instrumentId,
    assetType,
    name: input.name.trim(),
    ticker: assetType === "CASH" ? undefined : input.ticker?.trim() || undefined,
    exchange: assetType === "CASH" ? undefined : input.exchange?.trim() || undefined,
    isin: assetType === "CASH" ? undefined : input.isin?.trim() || undefined,
    nativeCurrency: baseCurrency,
  };
}

// Caller must validate first (validateHoldingFormInput) — this does not
// re-validate.
export function createHolding(
  input: HoldingFormInput,
  id: string,
  instrumentId: string,
  baseCurrency: string,
  asOf: string
): Holding {
  return {
    id,
    instrument: buildInstrument(input, input.assetType, instrumentId, baseCurrency),
    quantity: input.quantity,
    costBasis: buildCostBasis(input.assetType, input.averageCostNative, asOf),
  };
}

// Edits preserve the existing id and instrument.id (the join key to any
// linked StockPlaybookConfig or manual price — never regenerated) and the
// existing assetType (changing an existing holding's type is out of scope
// for v0.1; the form treats it as fixed once created, regardless of what
// the input carries).
export function updateHolding(existing: Holding, input: HoldingFormInput, asOf: string): Holding {
  const assetType = existing.instrument.assetType;
  return {
    ...existing,
    instrument: buildInstrument(input, assetType, existing.instrument.id, existing.instrument.nativeCurrency),
    quantity: input.quantity,
    costBasis: buildCostBasis(assetType, input.averageCostNative, asOf),
  };
}
